spring:
  resources:
    add-mappings: true
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.9:5432/usermanagement
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.default_schema: management
logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8567
